server:
  port: 8082

spring:
  application:
    name: MobileStoreApplication
  datasource:
    url: jdbc:mysql://localhost:3306/mobile_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true